// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvT4PRLw4VjpDuTgHdFbiA6-Xm_10IXEc',
    appId: '1:496478449602:web:f22500e38f591cbf25305b',
    messagingSenderId: '496478449602',
    projectId: 'f38bootcamp',
    authDomain: 'f38bootcamp.firebaseapp.com',
    storageBucket: 'f38bootcamp.appspot.com',
    measurementId: 'G-M5S7L49FL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-4AR3D8HSHot5QDLOxZiWKc2P-iVNt50',
    appId: '1:496478449602:android:782115460d3d47f225305b',
    messagingSenderId: '496478449602',
    projectId: 'f38bootcamp',
    storageBucket: 'f38bootcamp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDacXr9QO0X_W0EaO9NVZCwIifKQ2-2A4s',
    appId: '1:496478449602:ios:63979d786998e7ae25305b',
    messagingSenderId: '496478449602',
    projectId: 'f38bootcamp',
    storageBucket: 'f38bootcamp.appspot.com',
    iosClientId: '496478449602-ojo4le7smtctg7tevjqfusoev0agbatb.apps.googleusercontent.com',
    iosBundleId: 'com.example.f38',
  );
}
